version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:latest"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
    networks:
      - mynetwork

  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=Kliptopia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./database/DDL.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file=/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
networks:
  mynetwork:
    driver: bridge
